version: "3.9"

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # Persist downloaded models
    environment:
      - OLLAMA_MODELS=mistral         # Automatically load mistral on start
    restart: unless-stopped
    command: serve

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434  # ✅ connect to host's Ollama
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  ollama_models:
